version: '3'
services:
  api:
    container_name: api-gateway
    build: .
    ports: 
      - 3000:3000
    restart: on-failure
    volumes:
      - ./:/usr/src/app-api/
    networks:
      - fullstack
networks:
  fullstack:
    external: true

volumes:
  api:
  database_mysql:

